---
ops: [train, evaluate]
model: {
    path: <ABSOLUTE_PATH>/selene/manuscript/case2/deeper_deepsea_arch.py,
    class: DeeperDeepSEA,
    class_args: {  # DeeperDeepSEA.__init__ inputs
        sequence_length: 1000,
        n_targets: 919
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.MultiFileSampler {
    train_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_deepsea_mats/data/train.mat,
        sequence_key: trainxdata,
        targets_key: traindata,
        sequence_batch_axis: 2,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 1,
        shuffle: True,
        random_seed: 12
    },
    validate_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_deepsea_mats/data/valid.mat,
        sequence_key: validxdata,
        targets_key: validdata,
        sequence_batch_axis: 0,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 0,
        shuffle: False
    },
    test_sampler: !obj:selene_sdk.samplers.file_samplers.MatFileSampler {
        filepath: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_deepsea_mats/data/test.mat,
        sequence_key: testxdata,
        targets_key: testdata,
        sequence_batch_axis: 0,
        sequence_alphabet_axis: 1,
        targets_batch_axis: 0,
        shuffle: False
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: <ABSOLUTE_PATH>/selene/manuscript/case2/1_train_with_deepsea_mats/data/deepsea_predictor.names
    }
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 64,
    max_steps: 960000, 
    report_stats_every_n_steps: 64000,
    n_validation_samples: 8000,  # matches the number of samples in `valid.mat`
    n_test_samples: 455024,  # matches the number of samples in `test.mat`
    use_cuda: True,
    data_parallel: True,
    report_gt_feature_n_positives: 50,
    logging_verbosity: 2
}
output_dir: <ABSOLUTE_PATH>/selene/manuscript/case2/mat_training_outputs
random_seed: 1447
create_subdirectory: False
...
